# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

variables:
  homepage: ""

nix:
  - repository:
      owner: caarlos0
      name: nur
    homepage: "{{ with .Var.homepage }}{{ . }}{{ else }}https://github.com/caarlos0/{{ .ProjectName }}{{ end }}"
    description: "{{ .Var.description }}"
    license: mit

brews:
  - repository:
      owner: caarlos0
      name: homebrew-tap
    directory: Formula
    license: MIT
    homepage: "{{ with .Var.homepage }}{{ . }}{{ else }}https://github.com/caarlos0/{{ .ProjectName }}{{ end }}"
    description: "{{ .Var.description }}"

nfpms:
  - homepage: "{{ with .Var.homepage }}{{ . }}{{ else }}https://github.com/caarlos0/{{ .ProjectName }}{{ end }}"
    description: "{{ .Var.description }}"
    maintainer: Carlos Alexandro Becker <carlos@becker.software>
    license: MIT
    vendor: Becker Software
    formats:
      - apk
      - deb
      - rpm
