name: check

on:
  push:
  pull_request:

jobs:
  build.yml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: check -q -f build.yml
  docker.yml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: check -q -f docker.yml
  lib.yml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: check -q -f lib.yml
  package_with_completions.yml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: check -q -f package_with_completions.yml
  package.yml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: check -q -f package.yml
  podman.yml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: check -q -f podman.yml
  release.yml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: check -q -f release.yml
