name: check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser-pro
          install-only: true
      - name: check
        run: |
          goreleaser check -q *.yml
