name: check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: check *.yml
