name: check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: goreleaser install
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: --version
      - name: goreleaser check
        run: goreleaser --version
