name: check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: goreleaser check build.yml
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: check -q -f build.yml
      - name: goreleaser check docker.yml
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser-pro
          args: check -q -f docker.yml
