name: goreleaser

on:
  workflow_call:
    inputs:
      docker_username:
        required: true
        type: string
    secrets:
      docker_password:
        required: true
      gh_pat:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: sigstore/cosign-installer@v1.4.1
    - uses: anchore/sbom-action/download-syft@v0.6.0
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ secrets.docker_password }}
    - uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.gh_pat }}
